#! /usr/bin/python
# coding: utf-8

import SimpleHTTPServer
import SocketServer
import os
from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler
from SimpleHTTPServer import SimpleHTTPRequestHandler

class QuietSimpleHTTPRequestHandler(SimpleHTTPRequestHandler):
    """Quiet http request handler
    Subclasses SimpleHTTPRequestHandler in order to overwrite the log_message
    method, letting us reduce output generated by the handler. Only standard
    messages are overwritten, so errors will still be displayed.
    """
    def log_message(self, *args):
        """Drops messages intended to be printed
        """
        pass
def start():
    #server.daemon_threads = True
    web_dir = os.path.join(os.path.dirname(__file__), 'web')
    os.chdir(web_dir)
    httpd = HTTPServer(('', 7070), QuietSimpleHTTPRequestHandler)
    httpd.serve_forever()

start()
